server:
  port: 7001

eureka:
  instance:
    hostname: localhost   # eureka服务端的实例名称
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己
    fetch-registry: false   #false表示自己端就是注册中心
    service-url:
      # 单机,配置域名解析
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # 关闭自我保护机制，保证不可用服务被及时剔除
    enable-self-preservation: false 
    eviction-interval-timer-in-ms: 2000

spring:
  application:
    name: cloud-eureka-service

logging:
  level:
    com.netflix: warn
