
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

spring:
  application:
    name: micoserice-user
  zipkin:
    base-url: http://localhost:9994
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 9998