server:
  port: 8881

eureka:
  client:
    register-with-eureka: true   #是否将自己注册到注册中心,集群必须设置为true配合ribbon
    fetch-registry: true    #是否从服务端抓取已有的注册信息
    service-url:
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka  # 集群Eureka
  instance:
    instance-id: order-feign-80
    prefer-ip-address: true   #访问路径可以显示IP地址

spring:
  application:
    name: cloud-feign-order-service-80

#没提示不管它，可以设置
ribbon:
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  #指的是建立连接使用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ConnectTimeout: 5000
