server:
  port: 8080
# 指定服务命名
spring:
  application:
    name: consumer
  # 指定zipkin地址 默认就是http://localhost:9411/
  zipkin:
    base-url: http://localhost:9411/
# 指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
feign:
  hystrix:
    # 如果为true，则OpenFign客户端将使用Hystrix断路器进行封装 默认为false
    enabled: true