server:
  port: 7777

dubbo:
  application:
    ###########注册到注册中心的名称############
    name: goods
  ###########采用协议和端口号################
  protocol:
    ###########采用dubbo协议####################
    name: dubbo
    ###########发布dubbo端口号为20880###########
    port: 20881
  registry:
    ###########注册中心地址#####################
    address: zookeeper://localhost:2181
    ###########缓存文件#####################
    file: E://dubbo//provide/dubbo.cache


spring:
  output:
    ansi:
      enabled: always




