server:
  port: 9995

dubbo:
  application:
    ###########注册到注册中心的名称############
    name: balance
  ###########采用协议和端口号################
  protocol:
    ###########采用dubbo协议####################
    name: dubbo
    ###########发布dubbo端口号为20880###########
    port: 20882
  registry:
    ###########注册中心地址#####################
    address: zookeeper://localhost:2181

spring:
  output:
    ansi:
      enabled: always


