server:
  port: 8888

spring:
  application:
    name: sharding-sphere
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        dialect: sample.dynamic.datasource.config.CustomMySQL5Dialect
        format_sql: true
    show-sql: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    ordercenter:
      url: jdbc:mysql://127.0.0.1:3306/ordercenter?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver
    business:
      url: jdbc:mysql://127.0.0.1:3306/business?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.jdbc.Driver
