server:
  port: 8006

# 服务别名
spring:
  application:
    name: cloud-provider-payment-consul-8006  # #服务别名——注册到zookeeper注册中心的名称
  cloud:
    consul: # 配置连接信息
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

