server:
  port: 80

eureka:
  client:
    register-with-eureka: false   #是否将自己注册到注册中心,集群必须设置为true配合ribbon
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka

#设置feign客户端超时时间
ribbon:
  # 指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    #feiqn日志以什么级别监控哪个接口
    com.springcloud.service.PaymentFeignService: debug


spring:
  application:
    name: cloud-consumer-feign-order80
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public # 默认为 public，你可以指定其他 namespace
        # 如果需要用户名和密码进行认证，添加如下配置
        username: nacos
        password: nacos