
spring:
  application:
    name: micoserice-feign
  zipkin:
    base-url: http://localhost:9994
server:
   port: 8050
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
      instance-id: ${spring.application.name}:${server.port}
      prefer-ip-address: true
feign:
  hystrix:
    enabled: true
