server:
  port: 8081
spring:
  application:
    name: rabbitmq-producer
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
    amqp:
      deserialization:
        trust:
          all: true